# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

local_vars_file = File.join(File.dirname(__FILE__), "vars.yml")
local_vars      = YAML.load_file(local_vars_file)

ssh             = local_vars["ssh"]
vm              = local_vars["vm"]

Vagrant.configure("2") do |config|
    machines = local_vars["machines"]
    machines.each do |machine|
        config.vm.define machine["name"] do |conf|
            conf.vm.hostname = machine["name"]

            # VirtualBox Provider Config
            conf.vm.provider "virtualbox" do |v, override|
                override.vm.network vm["network"]["network"], type: vm["network"]["type"]

                override.vm.box = vm["box"]
                v.gui           = vm["options"]["gui"]
                v.memory        = vm["options"]["memory"]
                v.cpus          = vm["options"]["cpus"]
                v.linked_clone  = vm["options"]["linked_clone"]
            end
        end
    end

    if Vagrant.has_plugin?("vagrant-hostmanager")
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.manage_guest = true
    end
end